// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANu4Sr65mz_orDUoq52ZR7KUW6My2NIag',
    appId: '1:351374889391:web:4bce8ed9ecaadc39da1f5a',
    messagingSenderId: '351374889391',
    projectId: 'artiuosa',
    authDomain: 'artiuosa.firebaseapp.com',
    storageBucket: 'artiuosa.appspot.com',
    measurementId: 'G-YRY90PLM70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMrO6o8Sgs2gxilGNm1YSyttgpULnxGCg',
    appId: '1:351374889391:android:05a22f37d3f8ce0cda1f5a',
    messagingSenderId: '351374889391',
    projectId: 'artiuosa',
    storageBucket: 'artiuosa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu651ahGdo5l5xk2awonMmT_1qVzgTyXI',
    appId: '1:351374889391:ios:38dd0d0279c83f3cda1f5a',
    messagingSenderId: '351374889391',
    projectId: 'artiuosa',
    storageBucket: 'artiuosa.appspot.com',
    iosBundleId: 'com.example.artiuosa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu651ahGdo5l5xk2awonMmT_1qVzgTyXI',
    appId: '1:351374889391:ios:38dd0d0279c83f3cda1f5a',
    messagingSenderId: '351374889391',
    projectId: 'artiuosa',
    storageBucket: 'artiuosa.appspot.com',
    iosBundleId: 'com.example.artiuosa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANu4Sr65mz_orDUoq52ZR7KUW6My2NIag',
    appId: '1:351374889391:web:de9b494765e6984fda1f5a',
    messagingSenderId: '351374889391',
    projectId: 'artiuosa',
    authDomain: 'artiuosa.firebaseapp.com',
    storageBucket: 'artiuosa.appspot.com',
    measurementId: 'G-1T9PEYCXST',
  );
}
